### ISSUE TITLE
Logging solely to stdout/stderr at the specified log level

### ISSUE THREAD

**Issue by MaciekLeks** [mongodb/mongodb-kubernetes-operator#1439] opened 2023-11-26 08:20 UTC
**What did you do to encounter the bug?**
Unable to:
- Force logging of only ERRORs.
- Remove logs-volume PVC.

**What did you expect?**
I expected logging at the specified log level, directed solely to stdout, without creating a logs-volume PVC.

**What happened instead?**
- The agent logs at every level.
- A log-volume is created every time.

**Operator Information**
 - v0.8.3
 - crds v0.9.0
 - MongoDB - v7.0.3
-  agent 12.0.25.7724-1 

**Kubernetes Cluster Information**
 - GKE v1.25
 - internal registry 

My current yaml:
```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: test-mongodb
  namespace: common-mongodb
spec:
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  agent:
    logFile: /dev/stdout
    logLevel: ERROR
    systemLog:
      destination: file
      logAppend: true
      path: /dev/stdout
  members: 3
  security:
    authentication:
      ignoreUnknownUsers: true
      modes:
      - SCRAM
  statefulSet:
    spec:
      template:
        spec: { }
      volumeClaimTemplates:
      - metadata:
          name: data-volume
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
      #- metadata:
      #    name: logs-volume
      #  spec:
      #    accessModes:
      #    - ReadWriteOnce
      #    resources:
      #      requests:
      #        storage: 0Gi <--it can't be 0 :)
  type: ReplicaSet
  users:
  - db: admin
    name: admin
    passwordSecretRef:
      name: test-mongodb-admin-admin-cred
    roles:
    - db: admin
      name: clusterAdmin
    - db: admin
      name: userAdminAnyDatabase
    - db: admin
      name: root
    scramCredentialsSecretName: test-mongodb-admin-admin
  - db: eshop-order-db-int
    name: op
    passwordSecretRef:
      name: test-mongodb-eshop-order-db-int-op-cred
    roles:
    - db: eshop-order-db-int
      name: readWrite
    scramCredentialsSecretName: test-mongodb-eshop-order-db-int-op
  version: 7.0.3
```
P.S. I found related #1226 but it's not a solution to the whole problem.

**Comment by uttammeena** [comment] 2023-11-28 16:37
I am having the same issue after upgrading the mongodb-operator from 0.7.6 to 0.8.3.
By default it's logging as per AGENT_LOG_LEVEL to AGENT_LOG_FILE=/var/log/mongodb-mms-automation/automation-agent.log
However the moment I change AGENT_LOG_FILE=/dev/stdout it started logging everything like .trace as well as .debug
This is causing too much logging

**Comment by LinAnt** [comment] 2023-12-04 11:35
Damn, just deployed an operator upgrade and got paged that our log volumes are filling up with bloat...

**Comment by schans** [comment] 2023-12-04 11:43
The problem here seems to be that the mongo agent requires the absence of the logFile cmdline option to log to /dev/stdout. So if in the operator config the logFile is absent or set to /dev/stdout the cmdline should not include the logFile option part.

See: 
https://stackoverflow.com/questions/13506198/mongodb-log-mongod-to-stdout

Although the official docs do not mention this:
https://www.mongodb.com/docs/ops-manager/current/reference/mongodb-agent-settings/#logging-settings

**Comment by legal90** [comment] 2024-02-03 08:32
The issue is still actual

**Comment by uttammeena** [comment] 2024-02-05 20:35
Issue is still valid and blocking the upgrade of mongodb-operator from 0.7.8 onwards

**Comment by schans** [comment] 2024-02-10 23:50
Hi! Finally found some time to create a PR:

https://github.com/mongodb/mongodb-kubernetes-operator/pull/1489

The gist is that setting agent.logFile: /dev/stdout will unset the -logFile command line option which make the agent log to stdout.

Please review. Any comments welcome.

**Comment by nammn** [comment] 2024-03-01 09:42
@schans change has been merged. Closing this Issue

**Closed by nammn** 2024-03-01 09:42 UTC

**Comment by chadlangston** [comment] 2024-07-14 19:04
Thank you! This is a huge help 🙏
