### ISSUE TITLE
v0.5.1 Operator in "CrashLoopBackOff" status 

### ISSUE THREAD

**Issue by jwenjian** [mongodb/mongodb-kubernetes-operator#438] opened 2021-04-22 09:45 UTC
**What did you do to encounter the bug?**
1. `git clone https://github.com/mongodb/mongodb-kubernetes-operator.git`
2. `cd mongodb-kubernetes-operator`
3. `git checkout v0.5.1`
4. `kubectl apply -f config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml`
5. `kubectl apply -k config/rbac/ --namespace default`
6. `kubectl create -f config/manager/manager.yaml --namespace default`

> here I do a little update of the manager.yaml to change the imagePullPolicy from `Always` to `IfNotPresent`

7. kubectl get pod

**What did you expect?**
The operator pod is in Running status

**What happened instead?**
The operation pod is in CrashLoopBackOff status or Error status since too much restarts failed

**Screenshots**
> kubectl get pod

```
NAME                                           READY   STATUS             RESTARTS   AGE
mongodb-kubernetes-operator-5c66c499c4-hht6m   0/1     CrashLoopBackOff   8          20m

```

> kubectl describe pod

```
Name:         mongodb-kubernetes-operator-5c66c499c4-hht6m
Namespace:    default
Priority:     0
Node:         master.node/10.0.2.15
Start Time:   Thu, 22 Apr 2021 17:19:29 +0800
Labels:       name=mongodb-kubernetes-operator
              pod-template-hash=5c66c499c4
Annotations:  <none>
Status:       Running
IP:           10.244.0.16
IPs:
  IP:           10.244.0.16
Controlled By:  ReplicaSet/mongodb-kubernetes-operator-5c66c499c4
Containers:
  mongodb-kubernetes-operator:
    Container ID:  docker://85fdfac9e4a9e5cbd97c95fb313aab6423f5a66bd992a304ca11ac9f79f5fd0e
    Image:         quay.io/mongodb/mongodb-kubernetes-operator:0.5.1
    Image ID:      docker-pullable://quay.io/mongodb/mongodb-kubernetes-operator@sha256:69943ea7b3ed00e3faef6588fee2cfca80f491c3fd374ff529010f8d02637fa1
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/local/bin/entrypoint
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Thu, 22 Apr 2021 17:35:43 +0800
      Finished:     Thu, 22 Apr 2021 17:35:44 +0800
    Ready:          False
    Restart Count:  8
    Environment:
      WATCH_NAMESPACE:             default (v1:metadata.namespace)
      POD_NAME:                    mongodb-kubernetes-operator-5c66c499c4-hht6m (v1:metadata.name)
      OPERATOR_NAME:               mongodb-kubernetes-operator
      AGENT_IMAGE:                 quay.io/mongodb/mongodb-agent:10.27.0.6772-1
      VERSION_UPGRADE_HOOK_IMAGE:  quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.2
      MONGODB_IMAGE:               library/mongo
      MONGODB_REPO_URL:            registry.hub.docker.com
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-xtr8h (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-api-access-xtr8h:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  21m                 default-scheduler  Successfully assigned default/mongodb-kubernetes-operator-5c66c499c4-hht6m to master.node
  Normal   Pulled     19m (x5 over 20m)   kubelet            Container image "quay.io/mongodb/mongodb-kubernetes-operator:0.5.1" already present on machine
  Normal   Created    19m (x5 over 20m)   kubelet            Created container mongodb-kubernetes-operator
  Normal   Started    19m (x5 over 20m)   kubelet            Started container mongodb-kubernetes-operator
  Warning  BackOff    56s (x93 over 20m)  kubelet            Back-off restarting failed container

```
**Operator Information**
 - Operator Version: 0.5.1
 - MongoDB Image used: 4.2.3

**Kubernetes Cluster Information**
 - Distribution: kubeadm
 - Version: v1.21.0
 - Image Registry location (quay, or an internal registry): quay

**Additional context**

**Comment by chatton** [comment] 2021-04-22 09:51
Hi @jwenjian, thanks for the report.

I'm unable to reproduce this locally, would you be able to provide the logs of the crashing pod, using `kubectl logs <pod> -p` ?

**Comment by jwenjian** [comment] 2021-04-22 10:58
hello, I will post the log tomorrow morning。



发自我的iPhone


------------------ Original ------------------
From: Cian Hatton ***@***.***&gt;
Date: Thu,Apr 22,2021 5:52 PM
To: mongodb/mongodb-kubernetes-operator ***@***.***&gt;
Cc: Jiang Wenjian ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [mongodb/mongodb-kubernetes-operator] v0.5.1 Operator in "CrashLoopBackOff" status  (#438)





------------------ Original ------------------
From: Cian Hatton ***@***.***&gt;
Date: Thu,Apr 22,2021 5:52 PM
To: mongodb/mongodb-kubernetes-operator ***@***.***&gt;
Cc: Jiang Wenjian ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [mongodb/mongodb-kubernetes-operator] v0.5.1 Operator in &quot;CrashLoopBackOff&quot; status  (#438)





 
Hi @jwenjian, thanks for the report.
 
I'm unable to reproduce this locally, would you be able to provide the logs of the crashing pod, using kubectl logs <pod&gt; -p ?
 
&mdash;

**Comment by jwenjian** [comment] 2021-04-23 00:52
@chatton see logs below, only 2 lines

```
Running ./manager
2021-04-23T00:51:29.692Z        INFO    manager/main.go:71      Watching namespace: default

```

**Comment by jwenjian** [comment] 2021-04-23 08:08
@chatton additional context:

1. I setup the k8s cluster using kubeadm in a CentOS vm with a master node only, no worker node, all the pod will be scheduled at master node
2. total memory of the vm is 4Gb

**Comment by antonlisovenko** [comment] 2021-05-06 12:53
hi @jwenjian 

Do you still have this problem?

Have you tried the following:
- running the other kubernetes clusters locally. Kind/Minikube/k3s are the most common options. This would ensure there are no global environment problems affecting the work of the Operator and the error is specific to K8s cluster installed by `kubeadm` only.
- it's important to catch what real error is happening in the container - there's a [trick](https://docs.mongodb.com/kubernetes-operator/stable/reference/troubleshooting/#debug-a-failing-container) with overriding the command running in the container which allows to `kubectl exec` into the container and check what is happening there (and maybe trying to call the `/usr/local/bin/entrypoint` manually and see the output)

**Comment by jwenjian** [comment] 2021-05-10 02:13
hi @antonlisovenko , I switched to v0.6.0, it works, didn't try v0.5.1 yet

**Comment by antonlisovenko** [comment] 2021-05-17 08:02
Glad to hear this got fixed.
Closing the ticket then - feel free to reopen if you encounter the same issue.

**Closed by antonlisovenko** 2021-05-17 08:02 UTC
Labels: CLOUDP-88330

**Comment by j-lorenzo** [comment] 2021-06-07 17:05
Hi!,

This is happening to me in the version v0.6.0 right now.

Im using KIND

```
➜  mongodb-kubernetes-operator git:(9e35d2c) ✗ kubectl get all -n mongo
NAME                                               READY   STATUS   RESTARTS   AGE
pod/mongodb-kubernetes-operator-7b9d967646-pgblr   0/1     Error    4          2m1s

NAME                                          READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/mongodb-kubernetes-operator   0/1     1            0           2m1s

NAME                                                     DESIRED   CURRENT   READY   AGE
replicaset.apps/mongodb-kubernetes-operator-7b9d967646   1         1         0       2m1s
➜  mongodb-kubernetes-operator git:(9e35d2c) ✗ kubectl logs pod/mongodb-kubernetes-operator-7b9d967646-pgblr -n mongo
Running ./manager
```


```
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  3m25s                  default-scheduler  Successfully assigned mongo/mongodb-kubernetes-operator-7b9d967646-pgblr to kind-control-plane
  Normal   Pulled     3m11s                  kubelet            Successfully pulled image "quay.io/mongodb/mongodb-kubernetes-operator:0.6.0" in 14.016571895s
  Normal   Pulled     3m10s                  kubelet            Successfully pulled image "quay.io/mongodb/mongodb-kubernetes-operator:0.6.0" in 650.469741ms
  Normal   Pulled     2m53s                  kubelet            Successfully pulled image "quay.io/mongodb/mongodb-kubernetes-operator:0.6.0" in 743.842964ms
  Normal   Created    2m29s (x4 over 3m11s)  kubelet            Created container mongodb-kubernetes-operator
  Normal   Pulled     2m29s                  kubelet            Successfully pulled image "quay.io/mongodb/mongodb-kubernetes-operator:0.6.0" in 1.050394472s
  Normal   Started    2m28s (x4 over 3m11s)  kubelet            Started container mongodb-kubernetes-operator
  Warning  BackOff    110s (x8 over 3m9s)    kubelet            Back-off restarting failed container
  Normal   Pulling    99s (x5 over 3m25s)    kubelet            Pulling image "quay.io/mongodb/mongodb-kubernetes-operator:0.6.0"
```

**Comment by j-lorenzo** [comment] 2021-06-07 17:06
```
➜  mongodb-kubernetes-operator git:(9e35d2c) ✗ kubectl describe pod/mongodb-kubernetes-operator-7b9d967646-pgblr -n mongo
Name:         mongodb-kubernetes-operator-7b9d967646-pgblr
Namespace:    mongo
Priority:     0
Node:         kind-control-plane/172.18.0.2
Start Time:   Mon, 07 Jun 2021 19:01:37 +0200
Labels:       name=mongodb-kubernetes-operator
              pod-template-hash=7b9d967646
Annotations:  <none>
Status:       Running
IP:           10.244.0.5
IPs:
  IP:           10.244.0.5
Controlled By:  ReplicaSet/mongodb-kubernetes-operator-7b9d967646
Containers:
  mongodb-kubernetes-operator:
    Container ID:  containerd://2b747ffa81a626c6c41a74f991b8d6f8b87c10b6d25a35bcf8776822ded0b843
    Image:         quay.io/mongodb/mongodb-kubernetes-operator:0.6.0
    Image ID:      quay.io/mongodb/mongodb-kubernetes-operator@sha256:b3a9fd23f75990f327ec9ad5c745cec6f901a2c553a300c892d5866c6259a591
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/local/bin/entrypoint
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 07 Jun 2021 19:04:55 +0200
      Finished:     Mon, 07 Jun 2021 19:04:55 +0200
    Ready:          False
    Restart Count:  5
    Environment:
      mongo:                       mongo (v1:metadata.namespace)
      POD_NAME:                    mongodb-kubernetes-operator-7b9d967646-pgblr (v1:metadata.name)
      OPERATOR_NAME:               mongodb-kubernetes-operator
      AGENT_IMAGE:                 quay.io/mongodb/mongodb-agent:10.29.0.6830-1
      VERSION_UPGRADE_HOOK_IMAGE:  quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.2
      READINESS_PROBE_IMAGE:       quay.io/mongodb/mongodb-kubernetes-readinessprobe:1.0.3
      MONGODB_IMAGE:               library/mongo
      MONGODB_REPO_URL:            registry.hub.docker.com
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from mongodb-kubernetes-operator-token-8t5v8 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  mongodb-kubernetes-operator-token-8t5v8:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  mongodb-kubernetes-operator-token-8t5v8
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  4m13s                  default-scheduler  Successfully assigned mongo/mongodb-kubernetes-operator-7b9d967646-pgblr to kind-control-plane
  Normal   Pulled     3m59s                  kubelet            Successfully pulled image "quay.io/mongodb/mongodb-kubernetes-operator:0.6.0" in 14.016571895s
  Normal   Pulled     3m58s                  kubelet            Successfully pulled image "quay.io/mongodb/mongodb-kubernetes-operator:0.6.0" in 650.469741ms
  Normal   Pulled     3m41s                  kubelet            Successfully pulled image "quay.io/mongodb/mongodb-kubernetes-operator:0.6.0" in 743.842964ms
  Normal   Created    3m17s (x4 over 3m59s)  kubelet            Created container mongodb-kubernetes-operator
  Normal   Pulled     3m17s                  kubelet            Successfully pulled image "quay.io/mongodb/mongodb-kubernetes-operator:0.6.0" in 1.050394472s
  Normal   Started    3m16s (x4 over 3m59s)  kubelet            Started container mongodb-kubernetes-operator
  Warning  BackOff    2m38s (x8 over 3m57s)  kubelet            Back-off restarting failed container
  Normal   Pulling    2m27s (x5 over 4m13s)  kubelet            Pulling image "quay.io/mongodb/mongodb-kubernetes-operator:0.6.0"

```

**Comment by WatchLucky** [comment] 2021-12-15 06:13
I got the same error  。

logs as follow 

#kubectl logs -f mongodb-kubernetes-operator-5674959665-svfvw  -n   mongodb   
Running ./manager
2021-12-15T06:06:27.997Z        INFO    manager/main.go:74      Watching namespace: mongodb
2021-12-15T06:06:57.998Z        FATAL   manager/main.go:88      Unable to create manager: Get "https://10.96.0.1:443/api?timeout=32s": dial tcp 10.96.0.1:443: i/o timeout
main.main
        /workspace/cmd/manager/main.go:88
runtime.main
        /usr/local/go/src/runtime/proc.go:225


## 
#curl http://10.96.0.1:443 
Client sent an HTTP request to an HTTPS server.
