### ISSUE TITLE
Agents in each pod don't start after a fresh deployment

### ISSUE THREAD

**Issue by diogopainho** [mongodb/mongodb-kubernetes-operator#425] opened 2021-04-12 09:37 UTC
Good morning,
We deployed Mongo using the instructions described in: https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/deploy-configure.md#deploy-a-replica-set

However, we managed to have all the pods running, but the agents for each pod are in error.

NAME                                           READY   STATUS    RESTARTS   AGE
mongodb-0                                      1/2     Running   0          2d16h
mongodb-1                                      1/2     Running   0          2d16h
mongodb-2                                      1/2     Running   0          2d16h
mongodb-kubernetes-operator-5cf44c4478-d2jrm   1/1     Running   0          2d17h

Is it possible to help us understand what is going on?

When describing the pod I get the following error message: "Readiness probe failed:"

Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                        From     Message
  ----     ------     ----                       ----     -------
  Warning  Unhealthy  3m25s (x23355 over 2d16h)  kubelet  Readiness probe failed:

Thank you,
Best regards,
Diogo Rodrigues

**Comment by bznein** [comment] 2021-04-12 09:41
Hi @diogopainho,

can you provide us with the logs of the pods?

`kubectl logs mongodb-0 -c mongodb-agent` (and the same for pods 1 and 2), this might help us troubleshoot the issue

Nikolas

**Comment by diogopainho** [comment] 2021-04-12 09:46
Dear @bznein, 

Please find attached the requested logs. 

Thank you,
Best regards,
Diogo Rodrigues

[mongodb-0.log](https://github.com/mongodb/mongodb-kubernetes-operator/files/6295601/mongodb-0.log)
[mongodb-1.log](https://github.com/mongodb/mongodb-kubernetes-operator/files/6295602/mongodb-1.log)
[mongodb-2.log](https://github.com/mongodb/mongodb-kubernetes-operator/files/6295603/mongodb-2.log)

**Comment by bznein** [comment] 2021-04-19 16:03
Hi @diogopainho,

apologies for the delay.
If you still have the pods running, can you provide the content of the files in the following path:

`/var/log/mongodb-mms-automation/healthstatus`

Thanks!

**Comment by diogopainho** [comment] 2021-04-20 10:28
Dear @bznein , 

Please find in attachment the required logs. 

Thank you. 
[agent-health-status.zip](https://github.com/mongodb/mongodb-kubernetes-operator/files/6342742/agent-health-status.zip)

**Comment by bznein** [comment] 2021-04-20 11:11
Thanks @diogopainho,

from the file it looks like the readiness probe should not be failing.

Which version of the operator are you using?
Can you share the spec of your deployment?

Can you also share the following file?

`/var/log/mongodb-mms-automation/readiness`?

Thanks

**Comment by chatton** [comment] 2021-06-08 16:07
Hi @isbaran

What environment are you running the operator in?

 A pod security context with user 2000 is configured in the StatefulSet, my guess would be the security context is being modified in some way.

 Would you be able to provide us with the `describe` output for the StatefulSet?

**Comment by isbaran** [comment] 2021-06-08 16:20
Hello, running k8s 1.19.7 on Oracle Cloud, statefulset attached
[mongodb-statefulset.txt](https://github.com/mongodb/mongodb-kubernetes-operator/files/6618119/mongodb-statefulset.txt)

**Comment by chatton** [comment] 2021-06-09 08:09
Thanks @isbaran, would you also be able to provide the yaml output? `kubectl get sts <mdb-name> -o yaml` There are some fields I'm interested in that don't actually show up with just the `describe` output, thanks!

**Comment by isbaran** [comment] 2021-06-09 19:40
Sorry about that, yaml output attached
[mongodb-statefulset.txt](https://github.com/mongodb/mongodb-kubernetes-operator/files/6626456/mongodb-statefulset.txt)

**Comment by chatton** [comment] 2021-06-10 11:00
Hi @isbaran ,

Looking at the files you provided, the operator appears to be correctly configuring the pod security context

```yaml
      securityContext:
        fsGroup: 2000
```

However it looks like both PVCs are stuck in the `Pending` phase. I have never worked with Oracle Cloud, so I am not familiar with the CSI implementation in use there. 

The operator simply uses the default StorageClass.


I think there are two things that could be investigated

1. Does Oracle Cloud respect the configured security context
2. Oracle Cloud CSI / PV confiugration

**Comment by chatton** [comment] 2021-06-22 08:19
Hi @isbaran,

I'm closing this issue as we've been unable to reproduce it.

If you still have problems and can reproduce this in multiple environments please re-open and provide any additional repro steps you have, thanks!

**Closed by chatton** 2021-06-22 08:19 UTC
Labels: CLOUDP-87699
