### ISSUE TITLE
Mongo not starting

### ISSUE THREAD

**Issue by DeborggraeveR** [mongodb/mongodb-kubernetes-operator#721] opened 2021-09-17 13:50 UTC
**What did you do to encounter the bug?**

Followed the install instructions
https://github.com/mongodb/mongodb-kubernetes-operator/blob/b9487763041816f773d8dd01e1a5eb69dcf4a644/docs/install-upgrade.md

https://github.com/mongodb/mongodb-kubernetes-operator/blob/b9487763041816f773d8dd01e1a5eb69dcf4a644/docs/deploy-configure.md

**What did you expect?**
Running mongodb replicaset

**What happened instead?**
Mongod not starting cause the following files seem to be missing:
- /data/automation-mongod.conf
- /var/lib/mongodb-mms-automation/authentication/keyfile

**Operator Information**
```
randy@PC-HQ-01:~/k8smongo/mongodb-kubernetes-operator$ kubectl describe -n mongodb deployment.apps/mongodb-kubernetes-operator
Name:                   mongodb-kubernetes-operator
Namespace:              mongodb
CreationTimestamp:      Fri, 17 Sep 2021 15:18:57 +0200
Labels:                 owner=mongodb
Annotations:            deployment.kubernetes.io/revision: 1
                        email: support@mongodb.com
Selector:               name=mongodb-kubernetes-operator
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 25% max surge
Pod Template:
  Labels:           name=mongodb-kubernetes-operator
  Service Account:  mongodb-kubernetes-operator
  Containers:
   mongodb-kubernetes-operator:
    Image:      quay.io/mongodb/mongodb-kubernetes-operator:0.7.0
    Port:       <none>
    Host Port:  <none>
    Command:
      /usr/local/bin/entrypoint
    Limits:
      cpu:     1100m
      memory:  1Gi
    Requests:
      cpu:     500m
      memory:  200Mi
    Environment:
      WATCH_NAMESPACE:              (v1:metadata.namespace)
      POD_NAME:                     (v1:metadata.name)
      OPERATOR_NAME:               mongodb-kubernetes-operator
      AGENT_IMAGE:                 quay.io/mongodb/mongodb-agent:11.0.5.6963-1
      VERSION_UPGRADE_HOOK_IMAGE:  quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.2
      READINESS_PROBE_IMAGE:       quay.io/mongodb/mongodb-kubernetes-readinessprobe:1.0.4
      MONGODB_IMAGE:               mongo
      MONGODB_REPO_URL:            docker.io
    Mounts:                        <none>
  Volumes:                         <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   mongodb-kubernetes-operator-6b5c47996 (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  24m   deployment-controller  Scaled up replica set mongodb-kubernetes-operator-6b5c47996 to 1
```
```
randy@PC-HQ-01:~/k8smongo/mongodb-kubernetes-operator$ kubectl describe -n mongodb statefulset.apps/mongodb-specify-pod-resources
Name:               mongodb-specify-pod-resources
Namespace:          mongodb
CreationTimestamp:  Fri, 17 Sep 2021 15:19:43 +0200
Selector:           app=mongodb-specify-pod-resources-svc
Labels:             app=mongodb-specify-pod-resources-svc
Annotations:        <none>
Replicas:           3 desired | 3 total
Update Strategy:    RollingUpdate
Pods Status:        3 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app=mongodb-specify-pod-resources-svc
  Service Account:  mongodb-kubernetes-operator
  Init Containers:
   mongod-posthook:
    Image:      quay.io/mongodb/mongodb-kubernetes-operator-version-upgrade-post-start-hook:1.0.2
    Port:       <none>
    Host Port:  <none>
    Command:
      cp
      version-upgrade-hook
      /hooks/version-upgrade
    Environment:  <none>
    Mounts:
      /hooks from hooks (rw)
   mongodb-agent-readinessprobe:
    Image:      quay.io/mongodb/mongodb-kubernetes-readinessprobe:1.0.4
    Port:       <none>
    Host Port:  <none>
    Command:
      cp
      /probes/readinessprobe
      /opt/scripts/readinessprobe
    Environment:  <none>
    Mounts:
      /opt/scripts from agent-scripts (rw)
  Containers:
   mongod:
    Image:      docker.io/mongo:4.4.0
    Port:       <none>
    Host Port:  <none>
    Command:
      /bin/sh
      -c

      #run post-start hook to handle version changes
      /hooks/version-upgrade

      # wait for config and keyfile to be created by the agent
       while ! [ -f /data/automation-mongod.conf -a -f /var/lib/mongodb-mms-automation/authentication/keyfile ]; do sleep 3 ; done ; sleep 2 ;

      # with mongod configured to append logs, we need to provide them to stdout as
      # mongod does not write to stdout and a log file
      tail -F /var/log/mongodb-mms-automation/mongodb.log > /dev/stdout &

      # start mongod with this configuration
      exec mongod -f /data/automation-mongod.conf;


    Limits:
      cpu:     200m
      memory:  250M
    Requests:
      cpu:     200m
      memory:  200M
    Environment:
      AGENT_STATUS_FILEPATH:  /healthstatus/agent-health-status.json
    Mounts:
      /data from data-volume (rw)
      /healthstatus from healthstatus (rw)
      /hooks from hooks (rw)
      /var/lib/mongodb-mms-automation/authentication from mongodb-specify-pod-resources-keyfile (rw)
      /var/log/mongodb-mms-automation from logs-volume (rw)
   mongodb-agent:
    Image:      quay.io/mongodb/mongodb-agent:11.0.5.6963-1
    Port:       <none>
    Host Port:  <none>
    Command:
      /bin/bash
      -c
      current_uid=$(id -u)
      declare -r current_uid
      if ! grep -q "${current_uid}" /etc/passwd ; then
      sed -e "s/^mongodb:/builder:/" /etc/passwd > /tmp/passwd
      echo "mongodb:x:$(id -u):$(id -g):,,,:/:/bin/bash" >> /tmp/passwd
      export NSS_WRAPPER_PASSWD=/tmp/passwd
      export LD_PRELOAD=libnss_wrapper.so
      export NSS_WRAPPER_GROUP=/etc/group
      fi
      agent/mongodb-agent -cluster=/var/lib/automation/config/cluster-config.json -healthCheckFilePath=/var/log/mongodb-mms-automation/healthstatus/agent-health-status.json -serveStatusPort=5000 -skipMongoStart -noDaemonize -useLocalMongoDbTools
    Limits:
      cpu:     200m
      memory:  250M
    Requests:
      cpu:      200m
      memory:   200M
    Readiness:  exec [/opt/scripts/readinessprobe] delay=5s timeout=1s period=10s #success=1 #failure=40
    Environment:
      AGENT_STATUS_FILEPATH:  /var/log/mongodb-mms-automation/healthstatus/agent-health-status.json
      AUTOMATION_CONFIG_MAP:  mongodb-specify-pod-resources-config
      HEADLESS_AGENT:         true
      POD_NAMESPACE:           (v1:metadata.namespace)
    Mounts:
      /data from data-volume (rw)
      /opt/scripts from agent-scripts (rw)
      /var/lib/automation/config from automation-config (ro)
      /var/lib/mongodb-mms-automation/authentication from mongodb-specify-pod-resources-keyfile (rw)
      /var/log/mongodb-mms-automation from logs-volume (rw)
      /var/log/mongodb-mms-automation/healthstatus from healthstatus (rw)
  Volumes:
   agent-scripts:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
   automation-config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  mongodb-specify-pod-resources-config
    Optional:    false
   healthstatus:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
   hooks:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
   mongodb-specify-pod-resources-keyfile:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
Volume Claims:
  Name:          data-volume
  StorageClass:
  Labels:        <none>
  Annotations:   <none>
  Capacity:      10G
  Access Modes:  [ReadWriteOnce]
  Name:          logs-volume
  StorageClass:
  Labels:        <none>
  Annotations:   <none>
  Capacity:      2G
  Access Modes:  [ReadWriteOnce]
Events:
  Type    Reason            Age   From                    Message
  ----    ------            ----  ----                    -------
  Normal  SuccessfulCreate  25m   statefulset-controller  create Claim data-volume-mongodb-specify-pod-resources-0 Pod mongodb-specify-pod-resources-0 in StatefulSet mongodb-specify-pod-resources success
  Normal  SuccessfulCreate  25m   statefulset-controller  create Claim logs-volume-mongodb-specify-pod-resources-0 Pod mongodb-specify-pod-resources-0 in StatefulSet mongodb-specify-pod-resources success
  Normal  SuccessfulCreate  25m   statefulset-controller  create Pod mongodb-specify-pod-resources-0 in StatefulSet mongodb-specify-pod-resources successful
  Normal  SuccessfulCreate  24m   statefulset-controller  create Claim data-volume-mongodb-specify-pod-resources-1 Pod mongodb-specify-pod-resources-1 in StatefulSet mongodb-specify-pod-resources success
  Normal  SuccessfulCreate  24m   statefulset-controller  create Claim logs-volume-mongodb-specify-pod-resources-1 Pod mongodb-specify-pod-resources-1 in StatefulSet mongodb-specify-pod-resources success
  Normal  SuccessfulCreate  24m   statefulset-controller  create Pod mongodb-specify-pod-resources-1 in StatefulSet mongodb-specify-pod-resources successful
  Normal  SuccessfulCreate  24m   statefulset-controller  create Claim data-volume-mongodb-specify-pod-resources-2 Pod mongodb-specify-pod-resources-2 in StatefulSet mongodb-specify-pod-resources success
  Normal  SuccessfulCreate  24m   statefulset-controller  create Claim logs-volume-mongodb-specify-pod-resources-2 Pod mongodb-specify-pod-resources-2 in StatefulSet mongodb-specify-pod-resources success
  Normal  SuccessfulCreate  24m   statefulset-controller  create Pod mongodb-specify-pod-resources-2 in StatefulSet mongodb-specify-pod-resources successful
```

**Kubernetes Cluster Information**
- Type: on-premise
- Kubernetes v1.18.5
- Ubuntu server 18.04 LTS

**Additional context**
Using NFS storage + provisioner (https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner)
Data volume always empty
Logs volume contains file

**mongod container waiting for the missing files:**
```
randy@PC-HQ-01:~/k8smongo/mongodb-kubernetes-operator$ kubectl exec --stdin --tty -n mongodb mongodb-specify-pod-resources-0 -c mongod -- /bin/bash
groups: cannot find name for group ID 2000
2000@mongodb-specify-pod-resources-0:/$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
2000         1  0.0  0.0   4628  1636 ?        Ss   13:19   0:00 /bin/sh -c  #run post-start hook to handle version changes /hooks/version-upgrade  # wait for config and keyfile to be created by the agent  while ! [ -f /data/automation-m
2000       295  0.0  0.0  18508  3376 pts/0    Ss   13:33   0:00 /bin/bash
2000       303  0.0  0.0   4532   844 ?        S    13:33   0:00 sleep 3
2000       304  0.0  0.0  34404  2928 pts/0    R+   13:33   0:00 ps aux
```

**mongod container log**
```
randy@PC-HQ-01:~/k8smongo/mongodb-kubernetes-operator$ kubectl logs -n mongodb mongodb-specify-pod-resources-0 mongod
2021-09-17T13:19:50.841Z        INFO    versionhook/main.go:34  Running version change post-start hook
2021-09-17T13:19:50.841Z        INFO    versionhook/main.go:41  Waiting for agent health status...
2021-09-17T13:19:51.841Z        ERROR   versionhook/main.go:49  Error getting the agent health file: could not open file: open /healthstatus/agent-health-status.json: no such file or directory
main.main
        /go/cmd/versionhook/main.go:49
runtime.main
        /usr/local/go/src/runtime/proc.go:225
```

**mongodb-agent container log:**
```
randy@PC-HQ-01:~/k8smongo/mongodb-kubernetes-operator$ kubectl logs -n mongodb mongodb-specify-pod-resources-0 mongodb-agent
[2021-09-17T13:19:52.333+0000] [.info] [src/util/sysdep_unix.go:LockAutomationLockFile:321] [13:19:52.333] Locking automation lock file at /tmp/mongodb-mms-automation.lock
[2021-09-17T13:19:52.333+0000] [.info] [main/components/agent.go:NewAgent:123] [13:19:52.333] Constructing new agent object with desiredClusterConfigPath=/var/lib/automation/config/cluster-config.json
[2021-09-17T13:19:52.333+0000] [.info] [src/mongosqld/custodian.go:NewCustodian:138] <mongosqld custodian> [13:19:52.333] Started
[2021-09-17T13:19:52.335+0000] [.info] [realtime/rtcollector/rtcollector.go:controlLoop:87] <rtCollector> [13:19:52.335] Starting control loop
[2021-09-17T13:19:52.335+0000] [.info] [src/dataexplorer/dataexplorer.go:controlLoop:108] <dataExplorer> [13:19:52.335] Starting control loop
[2021-09-17T13:19:52.335+0000] [.info] [src/kmipproxy/custodian.go:mainLoop:205] <kmipProxyMaintainer> [13:19:52.335] Starting main loop
[2021-09-17T13:19:52.459+0000] [.info] [main/components/agent.go:LoadClusterConfig:259] [13:19:52.458] New cluster config received! 0 (<nil>) -> 1 (2021-09-17 13:19:45.453316698 +0000 UTC)
[2021-09-17T13:19:52.459+0000] [.info] [src/modules/agents_unix.go:KillAllAgents:42] [13:19:52.459] Killing all running mongodb-mms-monitoring-agent agents at /var/lib/mongodb-mms-automation/mongodb-mms-monitoring-agent-.+\..+_.+/mongodb-mms-monitoring-agent *$
[2021-09-17T13:19:52.461+0000] [.info] [src/modules/agents_unix.go:KillAllAgents:42] [13:19:52.461] Killing all running mongodb-mms-backup-agent agents at /var/lib/mongodb-mms-automation/mongodb-mms-backup-agent-.+\..+_.+/mongodb-mms-backup-agent *$
[2021-09-17T13:19:52.554+0000] [.info] [realtime/rtcollector/rtcollector.go:controlLoop:95] <rtCollector> [13:19:52.554] Received new cluster config!
[2021-09-17T13:19:52.555+0000] [.info] [src/dataexplorer/dataexplorer.go:controlLoop:114] <dataExplorer> [13:19:52.555] Received new cluster config!
[2021-09-17T13:19:52.627+0000] [.info] [src/maintainers/externalmaintainer.go:mainLoop:560] [13:19:52.627] Got a new descriptor for mongot
[2021-09-17T13:19:52.627+0000] [.info] [src/maintainers/externalmaintainer.go:mainLoop:560] [13:19:52.627] Got a new descriptor for atlasProxy
[2021-09-17T13:19:53.660+0000] [.info] [main/components/agent.go:Iterate:848] [13:19:53.660] All 0 Mongo processes are in goal state.
[2021-09-17T13:19:53.660+0000] [.info] [main/components/agent.go:LoadClusterConfig:262] [13:19:53.660] clusterConfig unchanged
[2021-09-17T13:20:03.698+0000] [.info] [main/components/agent.go:Iterate:848] [13:20:03.698] All 0 Mongo processes are in goal state.
[2021-09-17T13:20:03.698+0000] [.info] [main/components/agent.go:LoadClusterConfig:262] [13:20:03.698] clusterConfig unchanged
[2021-09-17T13:20:13.746+0000] [.info] [main/components/agent.go:Iterate:848] [13:20:13.746] All 0 Mongo processes are in goal state.
[2021-09-17T13:20:13.746+0000] [.info] [main/components/agent.go:LoadClusterConfig:262] [13:20:13.746] clusterConfig unchanged
[2021-09-17T13:20:23.756+0000] [.info] [main/components/agent.go:Iterate:848] [13:20:23.756] All 0 Mongo processes are in goal state.
[2021-09-17T13:20:23.756+0000] [.info] [main/components/agent.go:LoadClusterConfig:262] [13:20:23.756] clusterConfig unchanged
[2021-09-17T13:20:33.787+0000] [.info] [main/components/agent.go:Iterate:848] [13:20:33.787] All 0 Mongo processes are in goal state.
[2021-09-17T13:20:33.788+0000] [.info] [main/components/agent.go:LoadClusterConfig:262] [13:20:33.788] clusterConfig unchanged
[2021-09-17T13:20:43.807+0000] [.info] [main/components/agent.go:Iterate:848] [13:20:43.806] All 0 Mongo processes are in goal state.
[2021-09-17T13:20:43.807+0000] [.info] [main/components/agent.go:LoadClusterConfig:262] [13:20:43.807] clusterConfig unchanged
[2021-09-17T13:20:52.335+0000] [.info] [src/runtimestats/printer.go:mainLoop:58] <runtimestatsPrinter> [13:20:52.335] memory:rss=40554496
alloc=3881240   totalalloc=6498800      mallocs=44017   frees=17405     heapinuse=5308416       heapobjects=26612      gcpausetotalns=162453                                                                                                gcpauselastns=77333      gcnum=2 utimens=48510000        stimens=48510000        minflt=4068     majflt=0
```

All yaml files for deployment are taken from repository config/ folder
```
kubectl create ns mongodb
kubectl apply -f config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
kubectl apply -k config/rbac/ -n mongodb
kubectl apply -f config/manager/manager.yaml --namespace mongodb
kubectl apply -f config/samples/mongodb.com_v1_mongodbcommunity_specify_pod_resources.yaml -n mongodb
```

```
randy@PC-HQ-01:~/k8smongo/mongodb-kubernetes-operator$ kubectl get pvc -n mongodb
NAME                                          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS          AGE
data-volume-mongodb-specify-pod-resources-0   Bound    pvc-b2d50032-443f-49f9-b6f0-a43cd49c0f7c   10G        RWO            managed-nfs-storage   28m
data-volume-mongodb-specify-pod-resources-1   Bound    pvc-8b806598-abd2-4968-bc33-caf8dd9d8dee   10G        RWO            managed-nfs-storage   28m
data-volume-mongodb-specify-pod-resources-2   Bound    pvc-afa13f1a-3383-4c64-b4e2-76f40c019b7e   10G        RWO            managed-nfs-storage   27m
logs-volume-mongodb-specify-pod-resources-0   Bound    pvc-804c8354-46ba-40dd-b944-0bf9ade07083   2G         RWO            managed-nfs-storage   28m
logs-volume-mongodb-specify-pod-resources-1   Bound    pvc-c825c761-cb70-41c0-a54b-0c213336c4ee   2G         RWO            managed-nfs-storage   28m
logs-volume-mongodb-specify-pod-resources-2   Bound    pvc-ff39431f-ddca-48e3-b3ab-c5f682a81950   2G         RWO            managed-nfs-storage   27m
```

```
randy@PC-HQ-01:~/k8smongo/mongodb-kubernetes-operator$ kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS     CLAIM                                                 STORAGECLASS          REASON   AGE
pvc-804c8354-46ba-40dd-b944-0bf9ade07083   2G         RWO            Delete           Bound      mongodb/logs-volume-mongodb-specify-pod-resources-0   managed-nfs-storage            28m
pvc-8b806598-abd2-4968-bc33-caf8dd9d8dee   10G        RWO            Delete           Bound      mongodb/data-volume-mongodb-specify-pod-resources-1   managed-nfs-storage            28m
pvc-afa13f1a-3383-4c64-b4e2-76f40c019b7e   10G        RWO            Delete           Bound      mongodb/data-volume-mongodb-specify-pod-resources-2   managed-nfs-storage            27m
pvc-b2d50032-443f-49f9-b6f0-a43cd49c0f7c   10G        RWO            Delete           Bound      mongodb/data-volume-mongodb-specify-pod-resources-0   managed-nfs-storage            28m
pvc-c825c761-cb70-41c0-a54b-0c213336c4ee   2G         RWO            Delete           Bound      mongodb/logs-volume-mongodb-specify-pod-resources-1   managed-nfs-storage            28m
pvc-ff39431f-ddca-48e3-b3ab-c5f682a81950   2G         RWO            Delete           Bound      mongodb/logs-volume-mongodb-specify-pod-resources-2   managed-nfs-storage            27m
```

**Comment by irajdeep** [comment] 2021-09-22 07:45
Hi @DeborggraeveR 

Could you please share the `MongoDBCommunity` Custom Resource file, you're trying to apply.

**Comment by DeborggraeveR** [comment] 2021-09-22 08:14
@irajdeep 

I have been using the sample file: config/samples/mongodb.com_v1_mongodbcommunity_specify_pod_resources.yaml

Meanwhile i also run the same scenario on another cluster

**Kubernetes Cluster Information**
- Type: on-premise
- Kubernetes v1.21.1
- Ubuntu server 20.04 LTS

```
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb-specify-pod-resources
spec:
  members: 3
  type: ReplicaSet
  version: "4.4.0"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: my-user
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: my-scram
  statefulSet:
    spec:
      template:
        spec:
          # resources can be specified by applying an override
          # per container name.
          containers:
            - name: mongod
              resources:
                limits:
                  cpu: "0.2"
                  memory: 250M
                requests:
                  cpu: "0.2"
                  memory: 200M
            - name: mongodb-agent
              resources:
                limits:
                  cpu: "0.2"
                  memory: 250M
                requests:
                  cpu: "0.2"
                  memory: 200M
# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
type: Opaque
stringData:
  password: admin
```

These are the exact steps executed during deployment
```
git clone https://github.com/mongodb/mongodb-kubernetes-operator.git
cd mongodb-kubernetes-operator/
kubectl apply -f config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
kubectl create ns mongodb
kubectl apply -k config/rbac/ --namespace mongodb
kubectl create -f config/manager/manager.yaml --namespace mongodb
nano config/samples/mongodb.com_v1_mongodbcommunity_specify_pod_resources.yaml
kubectl apply -f  config/samples/mongodb.com_v1_mongodbcommunity_specify_pod_resources.yaml -n mongodb
```

**Comment by jatinderjawanda** [comment] 2021-09-22 18:38
Any Update on this one !!

**Comment by irajdeep** [comment] 2021-09-23 11:50
> These are the exact steps executed during deployment

```git clone https://github.com/mongodb/mongodb-kubernetes-operator.git
cd mongodb-kubernetes-operator/
kubectl apply -f config/crd/bases/mongodbcommunity.mongodb.com_mongodbcommunity.yaml
kubectl create ns mongodb
kubectl apply -k config/rbac/ --namespace mongodb
kubectl create -f config/manager/manager.yaml --namespace mongodb
nano config/samples/mongodb.com_v1_mongodbcommunity_specify_pod_resources.yaml
kubectl apply -f  config/samples/mongodb.com_v1_mongodbcommunity_specify_pod_resources.yaml -n mongodb```


Following the exact same steps in a [Kind cluster](https://kind.sigs.k8s.io/), I am not able to reproduce the issue. I would recommend first trying it out in a local `Kind` cluster and check if it works to isolate any infrastructure-related problems.

Also can you check the operator logs?

**Comment by jatinderjawanda** [comment] 2021-09-23 13:06
@irajdeep : I agree that these steps ran fine. Both operator pod and replica pod comes up. However the database is not starting inside the pod.
I raised a ticket for the same to get pointers.
https://github.com/mongodb/mongodb-kubernetes-operator/issues/730
```bash
I have no name!@mongodb-cluster-0:/$ mongo --tls --tlsCAFile /var/lib/tls/ca/ca.crt --tlsCertificateKeyFile /var/lib/tls/server/*.pem --host mongodb-cluster-svc.mongodb.svc.kubernetes.local
MongoDB shell version v4.4.6
connecting to: mongodb://mongodb-cluster-svc.mongodb.svc.kubernetes.local:27017/?compressors=disabled&gssapiServiceName=mongodb
Error: couldn't connect to server mongodb-cluster-svc.mongodb.svc.kubernetes.local:27017, connection attempt failed: SocketException: Error connecting to mongodb-cluster-svc.mongodb.svc.kubernetes.local:27017 (172.16.13.59:27017) :: caused by :: Connection refused :
connect@src/mongo/shell/mongo.js:374:17
@(connect):2:6
exception: connect failed
exiting with code 1
```

**Comment by irajdeep** [comment] 2021-09-23 13:09
@jatinderjawanda okay, we can have a look at that ticket, could you close this ticket in that case? It looks like a duplicate.
Thanks

**Comment by jatinderjawanda** [comment] 2021-09-23 13:12
@irajdeep : This ticket is opened by @DeborggraeveR.  

Regards !!

**Comment by irajdeep** [comment] 2021-09-23 13:16
Sorry missed that, @DeborggraeveR  are you having the similar issue of not able to connect or the mongodb pods are not running.

**Comment by jatinderjawanda** [comment] 2021-09-23 13:26
it seems @DeborggraeveR is also facing the same.
```bash
What happened instead?
Mongod not starting cause the following files seem to be missing:

/data/automation-mongod.conf
/var/lib/mongodb-mms-automation/authentication/keyfile
```

**Comment by DeborggraeveR** [comment] 2021-09-23 13:29
Yes, the files are missing, causing the mongod pod to wait for ever on these files.
From what i found, these files should be generated by the agent pod, but i don't find the reason why

**Comment by irajdeep** [comment] 2021-09-23 13:32
Thanks, folks. I am going to close this issue and we are going to investigate this as part of https://github.com/mongodb/mongodb-kubernetes-operator/issues/730.

**Closed by irajdeep** 2021-09-23 13:32 UTC
Labels: CLOUDP-100869
