### ISSUE TITLE
1. run all in docoment nut create secret to connection string 

### ISSUE THREAD

**Issue by refaelb** [mongodb/mongodb-kubernetes-operator#670] opened 2021-08-04 10:09 UTC
**What did you do to encounter the bug?**

**What did you expect?**

**What happened instead?**
A clear and concise description of what happened instead

**Screenshots**

**Operator Information**
 - Operator Version
 - MongoDB Image used

**Kubernetes Cluster Information**
 - Distribution
 - Version
 - Image Registry location (quay, or an internal registry)

**Additional context**

If possible, please include:
 - `kubectl describe` output
 - yaml definitions for your objects
 - log files for the operator and database pods

**Comment by chatton** [comment] 2021-08-09 07:47
Hi @refaelb,

It is not clear what your question is. Please provide as much information as possible and a clear description of what the issue is.

**Comment by chatton** [comment] 2021-08-16 08:20
closing issue as there is not enough information, feel free to re-open with more details if you need help.

**Closed by chatton** 2021-08-16 08:20 UTC
Labels: CLOUDP-97101
