### ISSUE TITLE
Cluster fails to elect a replica set primary if MongoDB version not in manifest

### ISSUE THREAD

**Issue by chris-hamper** [mongodb/mongodb-kubernetes-operator#271] opened 2021-01-03 17:20 UTC
**What did you do to encounter the bug?**
1. Deploy version `0.3.0` of the operator on a cluster
1. Create a mongodb resource that uses version `4.4.2` of Mongo DB:
    ```yaml
    apiVersion: mongodb.com/v1
    kind: MongoDB
    metadata:
      name: mongodb
    spec:
      members: 3
      type: ReplicaSet
      version: "4.4.2"
        security:
        authentication:
          modes: ["SCRAM"]
      users:
        - name: admin
          db: admin
          passwordSecretRef:
            name: passwords
            key: admin
          roles:
            - name: root
              db: admin
          scramCredentialsSecretName: admin
    ```
1. Attempt to connect to the cluster:
    ```bash
    $ kubectl run mongo --rm -it --image=mongo:4.4.2 -- \
      mongo 'mongodb://mongodb-svc.mongodb.svc.cluster.local:27017/?replicaSet=mongodb' \
      -u admin -p <password>
    If you don't see a command prompt, try pressing enter.

    {"t":{"$date":"2021-01-03T14:40:42.376Z"},"s":"I",  "c":"NETWORK",  "id":4333208, "ctx":"ReplicaSetMonitor-TaskExecutor","msg":"RSM host selection timeout","attr":{"replicaSet":"mongodb","error":"FailedToSatisfyReadPreference: Could not find host matching read preference { mode: \"nearest\" } for set mongodb"}}
    Error: connect failed to replica set mongodb/mongodb-svc.mongodb.svc.cluster.local:27017 :
    connect@src/mongo/shell/mongo.js:374:17
    @(connect):2:6
    exception: connect failed
    exiting with code 1
    ```

**What did you expect?**
The cluster would elect a replica set primary, and accept client connections.

Alternately, a validation error would be shown when I tried to create the `mongodb` resource with an unsupported version, or a clear error message indicating the unsupported version in the operator and/or agent logs. Mongo DB Pods don't become ready.

**What happened instead?**
MongoDB cluster status is `Running`:
```bash
$ kubectl get mongodb -n mongodb                                                
NAME      PHASE     VERSION
mongodb   Running   
```

Pods all appear to be OK:
```bash
$ kubectl get po -n mongodb
NAME                                           READY   STATUS    RESTARTS   AGE
mongodb-0                                      2/2     Running   0          14m
mongodb-1                                      2/2     Running   0          13m
mongodb-2                                      2/2     Running   0          12m
```

Connecting to the cluster fails as shown in steps to reproduce. The agent logs on the mongodb Pods show:
```bash
$  kubectl logs -n mongodb mongodb-0 mongodb-agent
[2021-01-03T14:46:55.827-00] [.error] [cm/main/cm.go:mainLoop:456] [14:46:55.827] Error loading desired cluster configs : [14:46:55.827] Error retrieving cluster config from '/var/lib/automation/config/cluster-config.json' : [14:46:55.827] Error validating syntax of cluster config : clusterConfig failed to validate:
&{builds 0xc000359640} : Invalid type. Expected: array, given: null
... (repeats)
```

**Operator Information**
 - Operator Version 0.3.0
 - MongoDB Image used 4.4.2

**Kubernetes Cluster Information**
 - Distribution: Ubuntu
 - Version: 20.04 LTS
 - Image Registry location: quay

**Additional context**

**Comment by chatton** [comment] 2021-02-16 17:42
Looks like a duplicate of #255

**Closed by chatton** 2021-02-16 17:42 UTC
Labels: CLOUDP-79683
