### ISSUE TITLE
Mongodb agent and tools binaries for arm64

### ISSUE THREAD

**Issue by kuznero** [mongodb/mongodb-kubernetes-operator#792] opened 2021-11-30 07:16 UTC
Similar to #712, also related to [this comment](https://github.com/mongodb/mongodb-kubernetes-operator/issues/299#issuecomment-982123979).

Is there an arm64 binary available that would be possible to use in a custom build targeting arm64?

I am looking into [Dockerfile.builder](ADD https://mciuploads.s3.amazonaws.com/mms-automation/mongodb-mms-build-agent/builds/automation-agent/prod/mongodb-mms-automation-agent-${agent_version}.${agent_distro}.tar.gz /data/mongodb-agent.tar.gz
ADD https://downloads.mongodb.org/tools/db/mongodb-database-tools-${tools_distro}-${tools_version}.tgz /data/mongodb-tools.tgz):

```
ADD https://mciuploads.s3.amazonaws.com/mms-automation/mongodb-mms-build-agent/builds/automation-agent/prod/mongodb-mms-automation-agent-${agent_version}.${agent_distro}.tar.gz /data/mongodb-agent.tar.gz
ADD https://downloads.mongodb.org/tools/db/mongodb-database-tools-${tools_distro}-${tools_version}.tgz /data/mongodb-tools.tgz
```

Are there arm64 binaries available for *mongodb-agent* and *mongodb-tools*?

**Comment by jasonmimick** [comment] 2021-12-13 20:31
Hi @kuznero -

We don't currently have any support for arm64 for the agents however it is in the roadmap. Would you be able to share any details on your requirements which could help us prioritize this issue?

Thanks,
Jason

**Comment by kuznero** [comment] 2021-12-14 08:43
Hi @jasonmimick,

I am running relatively big k8s cluster on arm64-based hardware. One of the corner stones of what I build is MongoDB. I am able to run plain MongoDB (v4.4) that runs smoothly on arm64, but as soon as I go to MongoDB 5, it starts reporting errors for missing CPU instructions (which I am not sure precise). The next step is to run k8s operator to govern MongoDB installations (which currently has very few small pieces missing).

Knowing that data centers around the globe will be employing arm64-based CPUs more and more going forward (thanks to Apple for paving the way with M1 Max), it makes sense MongoDB can run smoothly on most of arm64-based architectures (including Raspberry Pi 4 to allow wider adoption).

Hope those are good enough reasons to prioritize the support for arm64-based architecture better.

I would be happy to contribute if possible (granted minimal guidance from your side).

**Comment by jamesbroadhead** [comment] 2022-01-31 16:44
@kuznero thank you for this context - it helps us understand and make prioritization decisions. 

aarch64 builds of mongodb-tools are available here: https://www.mongodb.com/download-center/database-tools/releases/archive 
(note the use of "ARM 64" terminology). 

I have posted a link to an aarch64 build of the Agent on the original issue here: #299. 

We would welcome PRs to update the Operator to use these newer versions of the Agent and Tools, and support for aarch64 in general. Let us know if you encounter difficulties. If you post working Dockerfiles for images, we can add those to our CI. 

I'm going to close this ticket as a duplicate of #299, let's continue any other discussion there.

**Closed** 2022-01-31 16:48 UTC
Labels: CLOUDP-107027

**Comment by glebiller** [comment] 2022-04-18 17:49
@jamesbroadhead The mongodb-tools are available for ARM, but I can't find the mongodb-mms-automation-agent for ARM, is it available?

**Comment by Nilz11** [comment] 2022-11-21 16:42
@jamesbroadhead Would it be possible to add Debian ARM build as well? Atm only ubuntu is available.
