### ISSUE TITLE
Using the code of the tag 0.5.2, the example-mongodb-0 pod was not created successfully

### ISSUE THREAD

**Issue by hayazan** [mongodb/mongodb-kubernetes-operator#406] opened 2021-03-31 07:08 UTC
![image](https://user-images.githubusercontent.com/18796907/113104083-b2294000-9232-11eb-879f-c510d3e270af.png)
![image](https://user-images.githubusercontent.com/18796907/113104295-f3215480-9232-11eb-91ed-87f18339456f.png)

**Comment by hayazan** [comment] 2021-03-31 07:08
Error getting the agent health file: error opening file: open /healthstatus/agent-health-status.json: no such file or directory

**Comment by hayazan** [comment] 2021-03-31 07:16
![Uploading image.png…]()

**Comment by hayazan** [comment] 2021-03-31 07:19
![image](https://user-images.githubusercontent.com/18796907/113105736-8313ce00-9234-11eb-9089-40359cc47eec.png)

**Comment by hayazan** [comment] 2021-03-31 07:26
![image](https://user-images.githubusercontent.com/18796907/113106552-7a6fc780-9235-11eb-81b5-74bbd8d79ed6.png)

**Comment by bznein** [comment] 2021-03-31 07:27
Thanks for the information, I think I know what the issue is, I will get back to you soon

**Comment by hayazan** [comment] 2021-03-31 07:28
thanks

**Comment by bznein** [comment] 2021-03-31 18:53
Hi @hayazan, could you please look at this answer: https://github.com/mongodb/mongodb-kubernetes-operator/issues/410#issuecomment-811342372 and see if that fixes the issue? thanks!

**Comment by hayazan** [comment] 2021-04-01 02:06
> Hi @hayazan, could you please look at this answer: [#410 (comment)](https://github.com/mongodb/mongodb-kubernetes-operator/issues/410#issuecomment-811342372) and see if that fixes the issue? thanks!

Ok i try

**Comment by hayazan** [comment] 2021-04-01 02:49
> > Hi @hayazan, could you please look at this answer: [#410 (comment)](https://github.com/mongodb/mongodb-kubernetes-operator/issues/410#issuecomment-811342372) and see if that fixes the issue? thanks!
> 
> Ok i try

The pod is up, it's okay

**Comment by hayazan** [comment] 2021-04-01 02:50
> Hi @hayazan, could you please look at this answer: [#410 (comment)](https://github.com/mongodb/mongodb-kubernetes-operator/issues/410#issuecomment-811342372) and see if that fixes the issue? thanks!

The pod is up, it's okay

**Comment by hayazan** [comment] 2021-04-01 02:59
> Hi @hayazan, could you please look at this answer: [#410 (comment)](https://github.com/mongodb/mongodb-kubernetes-operator/issues/410#issuecomment-811342372) and see if that fixes the issue? thanks!



> Hi @hayazan, could you please look at this answer: [#410 (comment)](https://github.com/mongodb/mongodb-kubernetes-operator/issues/410#issuecomment-811342372) and see if that fixes the issue? thanks!

There is a new problem, the pod prompts [main] Error saving history file: FileOpenFailed: Unable to open() file /.dbshell: Permission denied
![image](https://user-images.githubusercontent.com/18796907/113237371-477f0f80-92d9-11eb-8dcd-fd78d0fdc888.png)
![image](https://user-images.githubusercontent.com/18796907/113237421-5d8cd000-92d9-11eb-9ac3-a7eedcac400a.png)

**Comment by bznein** [comment] 2021-04-01 13:03
Hi @hayazan, that looks like a Info message (it is marked with `I` and not with `E` as errors). Does it prevent you from achieving something?

If so, can you please open another issue? If this one is solved, can you close it?

Thanks

**Closed** 2021-04-02 01:59 UTC

**Comment by daxxog** [comment] 2021-07-31 13:38
I have gotten this same error on operator `v0.7.0` when attempting deploy a non-[semver](https://semver.org/) tag of MongoDB.

Investigating the logs of the operator gave me this:
```
ReplicaSet: failed to ensure AutomationConfig: could not build automation config: can't build the automation config: can't compute semver version from previous FeatureCompatibilityVersion
```

Deploying tag `4.0.26` instead of `4.0` fixed my issue.
