### ISSUE TITLE
cannot create a database other than default ones(local, config, admin)

### ISSUE THREAD

**Issue by ctheisingfl** [mongodb/mongodb-kubernetes-operator#1110] opened 2022-09-02 19:33 UTC
**What did you do to encounter the bug?**
1. Installed operator
2. ran this yaml file..
3. shelled into primary set
4.show dbs does not show my database I want to create

**What did you expect?**
show dbs:
- local
- admin
- config
- example-mondgodb

**What happened instead?**
show dbs:
- local
- admin
- config

**Screenshots**
```yaml

---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: example-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: ["SCRAM"]
    roles: # custom roles are defined here
      - role: listDatabases
        db: admin
        privileges:
          - resource:
              db: "example-mongodb"
              collection: "" # an empty string indicates any collection
            actions:
              - find
              - listDatabases
        roles: []
      - role: readChangeStream
        db: admin
        privileges:
          - resource:
              db: ""
              collection: "" # an empty string indicates any collection
            actions:
              - find
              - changeStream
        roles: []
  users:
    - name: admin
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: my-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: root
          db: admin
      scramCredentialsSecretName: my-scram5
    - name: dbz
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: dbz-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: readWrite
          db: example-mongodb #pass as variable
        - name: read
          db: local
        - name: read
          db: config
        - name: read
          db: admin
        - name: listDatabases
          db: admin
        - name: readChangeStream # apply the custom role to the user
          db: admin
      scramCredentialsSecretName: my-scram4
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: my-user-password
type: Opaque
stringData:
  password: <password>

---
apiVersion: v1
kind: Secret
metadata:
  name: dbz-password
type: Opaque
stringData:
  password: <password>


```

**Operator Information**
 - Operator Version
 - MongoDB Image used

**Kubernetes Cluster Information**
 - Distribution
 - Version
 - Image Registry location (quay, or an internal registry)

**Additional context**

If possible, please include:
 - `kubectl describe` output
 - yaml definitions for your objects
 - log files for the operator and database pods

**Comment by ctheisingfl** [comment] 2022-09-02 19:36
<img width="795" alt="Screen Shot 2022-09-02 at 3 35 41 PM" src="https://user-images.githubusercontent.com/100947421/188224863-2e98fcc4-54d9-4d92-84f3-356282af45bc.png">

**Comment by mircea-cosbuc** [comment] 2022-11-23 17:40
Hi @ctheisingfl , I'll close this issue as a duplicate of https://github.com/mongodb/mongodb-kubernetes-operator/issues/1112 . I replied there and we can keep the conversation going.

**Closed by mircea-cosbuc** 2022-11-23 17:40 UTC
Labels: triaged
