### ISSUE TITLE
secrets that contains users' connection strings and credentials are not created anymore

### ISSUE THREAD

**Issue by arshabh-inspectlogs** [mongodb/mongodb-kubernetes-operator#711] opened 2021-09-08 19:50 UTC
As per the [documentation](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/deploy-configure.md#deploy-a-replica-set) and the [release notes](https://github.com/mongodb/mongodb-kubernetes-operator/releases/tag/v0.6.1)

```
The Community Kubernetes Operator creates secrets that contains users' connection strings and credentials.
The secrets follow this naming convention: <metadata.name>-<auth-db>-<username>
```

Sadly, this is not true anymore in the latest code. We were able to get the above mentioned secret made in [release 0.6.1](https://github.com/mongodb/mongodb-kubernetes-operator/releases/tag/v0.6.1) but not when we cloned the latest codebase.

**Comment by trilliot** [comment] 2021-09-08 21:41
I had the same issue and it seems linked to #676.
The secret will not be created until the reconcilation loop succeeds, which is prevented by the mentioned issue.

**Comment by loserdog-err** [comment] 2021-09-09 02:26
+1

**Comment by mazzespazze** [comment] 2021-09-09 13:40
+1

**Comment by mazzespazze** [comment] 2021-09-09 13:42
Any insight in how to connect then to mongodb?

**Comment by arshabh-inspectlogs** [comment] 2021-09-09 14:28
@mazzespazze I used release 0.6.1. It worked

**Comment by mswilson4040** [comment] 2021-09-10 20:50
+1

Working my way through the documentation [here](https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/deploy-configure.md#deploy-a-replica-set) and can't make much progress since the below command can't find the secret. The replica set and secret within the yaml file here deploy without issue.

Doesn't work:
```
kubectl get secret <metadata.name>-<auth-db>-<username> -n <my-namespace> \ 
-o json | jq -r '.data | with_entries(.value |= @base64d)'
```

Is there a manual way to get the operator to generate the secret?

**Comment by tibulca** [comment] 2021-09-15 10:35
Hi @arshabh-inspectlogs, @trilliot,
found the regression and fixed it on master, can you please pull the latest changes and try again?

**Comment by trilliot** [comment] 2021-09-15 12:57
Hello @tibulca,
I can confirm the issue is fixed on master.

```
NAME                                      TYPE                                  DATA   AGE
example-mongodb-admin-my-user             Opaque                                4      75s
example-mongodb-agent-password            Opaque                                1      3m46s
example-mongodb-config                    Opaque                                1      3m46s
example-mongodb-keyfile                   Opaque                                1      3m46s
```

Thank you very much :raised_hands:

**Closed** 2021-09-21 19:06 UTC
Labels: CLOUDP-100089
