### ISSUE TITLE
Connection String Host Improvement

### ISSUE THREAD

**Issue by shantanubansal** [mongodb/mongodb-kubernetes-operator#146] opened 2020-08-20 22:11 UTC
Hey,
Is it possible to access all the nodes in ReplicaSet with just a single Service Name? This will be very useful.?
Suppose My ReplicaSet are pod:
 `mongo-0
   mongo-1
   mongo-2`.
So to access them I will have a host 
`mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27107`
Instead of this if we will be able to do just
`mongodb://mongo:27107`
that would be cool. As we won't have to change the client connection string whenever we scale up or down.

PS: Here `mongo` is the service

**Comment by antonlisovenko** [comment] 2020-08-21 08:11
hi @shantanubansal 

DB url string must conform to requirements by MongoDB: https://docs.mongodb.com/manual/reference/connection-string/
The standard way is to list the hosts in the URL. But there is the way to make this more scalable in case of changes in topology: just use the SRV records: https://docs.mongodb.com/manual/reference/connection-string/#dns-seedlist-connection-format 
In Kubernetes you need to use the FQDN service name as the hostname in this case

**Comment by shantanubansal** [comment] 2020-08-24 05:18
hi @antonlisovenko ,
I get that. But should not be the feature out of the box from the operator? Because this abstraction makes it very simple for the person who gonna use this operator. People using operator should not be worried about all this. They should just go and provide the details of number of replicaset and users and out of the box they should get the details. Just a thought! as a mongoDB user (External service or Internal service) I should not be worried about changing services.

**Comment by theburi** [comment] 2020-08-24 11:43
Can I clarify one point here. The operator does create a K8s service and that service creates SRV records automatically in K8S DNS. That SRV record is updated every time STS scales up or down.
so the connection string that can be used is mongodb+srv://<crd name>-svc.<namespace>.svc.cluster.local/...

There is an outstanding feature we need is to expose that string automatically in CRD object or create a concept of "Binding". As a first step, we will expose this connection string in MongoDB CRD Status so it could be referenced.

Exposing that Service externally is a bit trickier as we really don't have a good solution for TCP ingress (for Replicaset). We are looking into Istio but we need to run a few more experiments.

**Comment by ubergeek77** [comment] 2020-08-25 05:10
I'm a little confused about how this works. I've created a ReplicaSet using the very basic config referenced from the README:

```
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: example-mongodb
spec:
  members: 3
  type: ReplicaSet
  version: "4.2.6"
```

This creates everything automatically (the StatefulSet, Service, Volumes, etc).

In a debugging Pod with access to the cluster's DNS records, I can successfully ping this host:

```
example-mongodb-svc.mongodb.svc.cluster.local
```

As far as I'm aware (and please correct me if I am wrong), this hostname represents *all of the Pods in the StatefulSet,* not any single Pod.

If I use a tool such as `dig` to query the SRV record of the above host, it correctly returns the SRV records, as expected:

```
> dig SRV example-mongodb-svc.mongodb.svc.cluster.local
---
...
example-mongodb-svc.mongodb.svc.cluster.local. 5 IN SRV 0 33 27017 example-mongodb-0.example-mongodb-svc.mongodb.svc.cluster.local.
example-mongodb-svc.mongodb.svc.cluster.local. 5 IN SRV 0 33 27017 example-mongodb-1.example-mongodb-svc.mongodb.svc.cluster.local.
example-mongodb-svc.mongodb.svc.cluster.local. 5 IN SRV 0 33 27017 example-mongodb-2.example-mongodb-svc.mongodb.svc.cluster.local.
...

```

However, if I attempt to connect using `+srv`, I receive the following error:

```
> mongo 'mongodb+srv://example-mongodb-svc.mongodb.svc.cluster.local/?tls=false'
---
DNSHostNotFound: Failed to look up service "_mongodb._tcp.example-mongodb-svc.mongodb.svc.cluster.local": Success
try 'mongo --help' for more information
```

Confusingly, if I *omit the `+srv` from the URI string,* I can connect with no issue:

```
mongo 'mongodb://example-mongodb-svc.mongodb.svc.cluster.local/?tls=false'
---
...
example-mongodb:PRIMARY>
```

However, I suspect that this is not the intended/correct way of accessing multiple MongoDB instances replicated like this.

Given this, the questions I have are:
- Did I do anything wrong?
- If I refer to a replicated MongoDB service by name *without using `+srv`*, will a MongoDB client properly use all replicas? Or will the first replica receive all the incoming load?

**Comment by theburi** [comment] 2020-08-25 08:29
We have seen some issues with older drivers not supporting SRV (bugs) and some K8S DNS implementation have not been compliant with RFC2782. 
What K8S distro are you using (and version) and what MongoDB Driver (version)? We could try to reproduce.

**Comment by ubergeek77** [comment] 2020-08-25 09:40
I am using `microk8s` version `1.16.14`. I will be moving my deployments to GKE once I'm done creating and testing them, so I chose this version of `microk8s` to have parity with Google's "default" version for GKE. The host machine for `microk8s` is Ubuntu 20.04.

My in-cluster debugging container is a Pod created from the `ubuntu:20.04` image, with MongoDB installed via the following guide:

https://www.howtoforge.com/how-to-install-and-use-mongodb-on-ubuntu-2004/

If you wanted to reproduce my exact environment, you would:

- Install `microk8s 1.16.14` on an Ubuntu 20.04 host
- Run through the steps to install the MongoDB operator, as per the README in this repository (I left everything unchanged and at their default values)
- As per the README, deploy `example-mongodb` (I have also copied this config in my above comment)
- Install an `ubuntu:20.04` debugging container for shell access. The easiest way to do so is to run the following command:

```
kubectl run -it --rm --restart=Never ubuntu --image=ubuntu:20.04 bash
```
Then, from the Ubuntu Pod:
- Install MongoDB via the link I posted above; this yields MongoDB version 4.2.9 (slightly newer than the one in the cluster)
- Install `iputils-ping` and `dnsutils` and perform the `ping` and `dig` checks I have posted above
- Finally, attempt to connect to `example-mongodb` via the `mongo` binary. By using the two URI's (one with and one without `+srv`), you should be able to reproduce the behavior I described above.

I've just run through these steps again before posting, and I can confirm these steps lead to this behavior.

So, as you can see, I'm not using an outdated version of MongoDB, and as the `dig` check shows, the `SRV` records are being set correctly.

**Comment by ubergeek77** [comment] 2020-08-26 03:01
I have found out exactly what causes this, and I've found the solution.

MongoDB [adheres very strictly](https://jira.mongodb.org/browse/DRIVERS-521) to RFC 2782's naming conventions, and as such, it *requires* the *service name* in the SRV record to be *exactly* `mongodb`. It cannot be anything else.

As of [MongoDB Kubernetes Operator v0.1.1](https://github.com/mongodb/mongodb-kubernetes-operator/tree/v0.1.1), Kubernetes services created for MongoDB databases *do not set the port name*. Look at the following excerpt obtained when running the command `kubectl get svc -n mongodb -o=yaml`:

```
...
spec:
    clusterIP: None
    ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
    selector:
      app: example-mongodb-svc
...
```

Notice how there is no `name` set for the port. By omitting this name, and by not setting it to `mongodb`, the resulting SRV records that get created from this are non-compliant to MongoDB clients.

The solution is to simply set the port `name` to `mongodb`. The "hack" way to do this for debugging would be to:

- Export the config for the service: `kubectl get svc -n mongodb -o=yaml > svc-to-modify.yaml`
- Modify the .yaml to set the port `name` to `mongodb`
- Apply the modified .yaml: `kubectl apply -f svc-modified.yaml`

After doing so, MongoDB clients in the cluster will *immediately* be able to connect to MongoDB Operator-managed databases via SRV records. I just tried this and it works:

```
root@ubuntu:/# mongo 'mongodb+srv://example-mongodb-svc.mongodb.svc.cluster.local/?tls=false&ssl=false'
---
MongoDB shell version v4.2.9
connecting to: mongodb://example-mongodb-0.example-mongodb-svc.mongodb.svc.cluster.local:27017,example-mongodb-1.example-mongodb-svc.mongodb.svc.cluster.local:27017,example-mongodb-2.example-mongodb-svc.mongodb.svc.cluster.local:27017/?compressors=disabled&gssapiServiceName=mongodb&ssl=false&tls=false
...
example-mongodb:PRIMARY>
```

For what it's worth, [KubeDB is also guilty of this](https://kubedb.com/docs/v0.13.0-rc.0/guides/mongodb/quickstart/quickstart/). They set the port `name` to `db`, but doing so is non-compliant to MongoDB clients, at least when SRV records are to be used.

So, as far as this repository is concerned, setting the port `name` to `mongodb` appears to solve this issue completely.

It's strange to me that, not only was this not caught sooner, KubeDB also "improperly" sets the port name. And despite both of these things, I could not find a single issue report of this ever being addressed in KubeDB's issue tracker, this issue tracker, or anywhere else. Either my Google-Fu is rusty, or literally no one has brought up this Kubernetes-specific issue before. Because of this, I have to think something must be going over my head here, but the solution I found does seem very straightforward.

While I'm here, I must say [I completely agree with the comments of this issue](https://github.com/mongodb/mongodb-kubernetes-operator/issues/146); MongoDB's behavior of forcing the service name to be a certain name is 100% unnecessarily restrictive. *Defaulting* to `mongodb` is fine, but I should be able to override it if I want to.

In any case, assuming this is a valid bug/oversight that will be fixed in a future version of MongoDB Kubernetes Operator, is there any way to fix this at deploy-time in the current version of the Operator without having to export and import configurations manually?

**Comment by antonlisovenko** [comment] 2020-08-26 07:59
Hi @ubergeek77 

Thanks for your detailed analysis!
Sorry for misleading you, we do set the port name to `mongodb` in the Enterprise Operator so connecting over `srv` records is possible there, but not in the Community Operator. 
Not sure if there is a way to fix this now except for manual changing of the services specification. 
We'll discuss if we can address this issue soon, thank you again!

**Closed** 2021-01-07 11:44 UTC
Labels: CLOUDP-78299
